export const lixeirasTestesE1 = [
  {
    id: "teste0",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 10,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 10,
    estacao: "E1",
  },
  {
    id: "teste1",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 20,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 20,
    estacao: "E1",
  },
  {
    id: "teste2",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 30,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 30,
    estacao: "E1",
  },
  {
    id: "teste3",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 30,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 30,
    estacao: "E1",
  },
];

export const lixeirasTestesE2 = [
  {
    id: "teste4",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 40,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 40,
    estacao: "E2",
  },
  {
    id: "teste5",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 50,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 50,
    estacao: "E2",
  },
  {
    id: "teste6",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 60,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 60,
    estacao: "E2",
  },
  {
    id: "teste7",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 70,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 70,
    estacao: "E2",
  },
];

export const lixeirasTestesE3 = [
  {
    id: "teste8",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 80,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 80,
    estacao: "E3",
  },
  {
    id: "teste9",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 90,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 90,
    estacao: "E3",
  },
  {
    id: "teste10",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 100,
    quantidadeLixoMaxima: 100,
    ocupacaoAtual: 100,
    estacao: "E3",
  },
  {
    id: "teste11",
    longitude: 10.0,
    latitude: 10.0,
    quantidadeLixoAtual: 110,
    quantidadeLixoMaxima: 150,
    ocupacaoAtual: 73,
    estacao: "E3",
  },
];
